# Site settings
title: "Eloquent Javascript"
email: "randsonjs@gmail.com"
description: "A portuguese translation of Eloquent JavaScript 2 edition by Marijn Haverbeke"
baseurl: "/eloquente-javascript"
url: "http://braziljs.github.io/eloquente-javascript/"

# Build settings
markdown: kramdown

source: .
destination: ./_site
plugins_dir: ./_plugins
paginate: 5
paginate_path: "blog/page:num"

permalink: /:title/

sass:
    sass_dir: ./assets/sass
    style: :compressed

webrick:
  headers:
    Content-Security-Policy: default-src * 'unsafe-inline' 'unsafe-eval'; script-src * 'unsafe-inline' 'unsafe-eval'; connect-src * 'unsafe-inline'; frame-src *;
